module.exports = {
    env: process.env.NODE_ENV,
    dbOptions: { useUnifiedTopology: true , useNewUrlParser: true },
    dbUrl: process.env.DB_URL,
    dbUrlTest: process.env.DB_URL_TEST,
    redisUrl: process.env.REDIS_URL,
    spikeUrl: process.env.SPIKE_URL,
    spikeAudience: process.env.AUDIENCE_G,
    kartoffelUrl: process.env.KARTOFFEL_URL,
    kartingUrl: process.env.KARTING_URL,
    targetOrchUrl: process.env.TARGET_ORCH_URL,
    targetOrchUser: process.env.TARGET_ORCH_USER,
    targetOrchPass: process.env.TARGET_ORCH_PASS,
    kafkaBrokers: process.env.KAFKA_BROKERS,
    kafkaTopic: process.env.KAFKA_TOPIC,
    kafkaGroupId: process.env.GROUPID,
    kafkaClientId: process.env.CLIENTID,
    httpPort: 8000,
    specialDomain: 'dataSource1',
    specialMailServer: 'hahaha.com',
    targetDomain: 'damoi.com',
    auth: false,
    isMock: false,
}