name: auto deploy node app to azure server
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: connect and deploy the app
      uses: appleboy/ssh-action@master
      with: 
        host: 20.71.138.217
        username: migration
        # key: ${{ secrets.MIGRATIONSECRET }}
        password: ${{ secrets.MIGRATION_PASSWORD }}
        port: 22
        script: |
          cd helpmefindname
          git pull origin master
          git status
          npm install
          pm2 restart 0
